import type { MenuItem, SiteConfig } from './types';

export const defaultConfig: SiteConfig = {
  businessName: 'El Fogón Dorado',
  logoUrl: '',
  phone: '+593 99 999 9999',
  address: 'Av. Principal 123, Ciudad',
  slogan: 'De la tarde al fuego nocturno',
};

export const defaultMenu: MenuItem[] = [
  {
    id: '1',
    name: 'Bolón de Verde Mixto',
    description: 'Bolón de plátano verde relleno de queso y chicharrón, acompañado de huevo frito y café',
    price: 5.50,
    category: 'tarde',
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&q=80',
    available: true,
  },
  {
    id: '2',
    name: 'Empanadas de Viento',
    description: 'Empanadas crujientes rellenas de queso, servidas con azúcar espolvoreada y ají',
    price: 3.50,
    category: 'tarde',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&q=80',
    available: true,
  },
  {
    id: '3',
    name: 'Humitas con Café',
    description: 'Humitas de choclo tierno envueltas en hoja de maíz, servidas con café pasado',
    price: 4.00,
    category: 'tarde',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500&q=80',
    available: true,
  },
  {
    id: '4',
    name: 'Tortillas de Maíz',
    description: 'Tortillas doradas de maíz con queso fresco derretido y ají de tomate de árbol',
    price: 4.50,
    category: 'tarde',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&q=80',
    available: true,
  },
  {
    id: '5',
    name: 'Muchines de Yuca',
    description: 'Croquetas crujientes de yuca rellenas de queso con salsa de ají',
    price: 3.00,
    category: 'tarde',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=500&q=80',
    available: true,
  },
  {
    id: '6',
    name: 'Morocho con Empanada',
    description: 'Bebida espesa de morocho dulce con canela acompañada de empanada de viento',
    price: 4.50,
    category: 'tarde',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500&q=80',
    available: true,
  },
  {
    id: '7',
    name: 'Parrillada Completa',
    description: 'Lomo, chuleta, chorizo, morcilla, pollo y costilla a la parrilla con guarniciones',
    price: 25.00,
    category: 'noche',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=500&q=80',
    available: true,
  },
  {
    id: '8',
    name: 'Costillas BBQ',
    description: 'Costillas de cerdo bañadas en salsa BBQ ahumada, cocidas a fuego lento por 6 horas',
    price: 18.00,
    category: 'noche',
    image: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=500&q=80',
    available: true,
  },
  {
    id: '9',
    name: 'Lomo al Carbón',
    description: 'Corte premium de lomo fino asado al carbón, término a elección, con papas al horno',
    price: 22.00,
    category: 'noche',
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=500&q=80',
    available: true,
  },
  {
    id: '10',
    name: 'Chuleta Ahumada',
    description: 'Chuleta de cerdo ahumada con salsa criolla, maduro asado y ensalada fresca',
    price: 15.00,
    category: 'noche',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=500&q=80',
    available: true,
  },
  {
    id: '11',
    name: 'Pollo a la Brasa',
    description: 'Medio pollo marinado en hierbas y especias, asado a las brasas con chimichurri',
    price: 12.00,
    category: 'noche',
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=500&q=80',
    available: true,
  },
  {
    id: '12',
    name: 'Chorizo Artesanal',
    description: 'Chorizos artesanales a la parrilla con papas doradas, ensalada y ají de la casa',
    price: 10.00,
    category: 'noche',
    image: 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=500&q=80',
    available: true,
  },
];
